//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapSite2
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogLeads
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Lastname { get; set; }
        public string Email { get; set; }
        public string ClientIP { get; set; }
        public string RegistrationDate { get; set; }
        public string Company { get; set; }
        public string LeadType { get; set; }
        public string LeadIs { get; set; }
        public string Occupation { get; set; }
    }
}
