//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapSite2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public System.Guid Id { get; set; }
        public System.Guid StudentId { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> IsAnonymous { get; set; }
        public Nullable<bool> IsPublic { get; set; }
    
        public virtual Students Students { get; set; }
    }
}
