//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapSite2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int companyId { get; set; }
        public string fullName { get; set; }
        public string email { get; set; }
        public string companyName { get; set; }
        public string companyType { get; set; }
        public string companySize { get; set; }
        public string identityId { get; set; }
        public Nullable<System.Guid> CompanyGuid { get; set; }
        public Nullable<System.DateTime> DataRegistro { get; set; }
        public string Facebook { get; set; }
        public string Instagram { get; set; }
        public string Linkedin { get; set; }
        public string Twitter { get; set; }
    }
}
