//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapSite2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class doutormidiaEntities : DbContext
    {
        public doutormidiaEntities()
            : base("name=doutormidiaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Facebook> Facebook { get; set; }
        public virtual DbSet<Instagram> Instagram { get; set; }
        public virtual DbSet<Linkedin> Linkedin { get; set; }
        public virtual DbSet<Twitter> Twitter { get; set; }
    }
}
