//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapSite2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Linkedin
    {
        public int Id { get; set; }
        public Nullable<int> Seguidores { get; set; }
        public Nullable<double> MediaPostSemana { get; set; }
        public Nullable<double> MediaCurtidasPost { get; set; }
        public Nullable<double> MediaImpressoesPost { get; set; }
        public string UserEmail { get; set; }
        public Nullable<System.Guid> CompanyGuid { get; set; }
        public Nullable<double> NewSeguidores { get; set; }
    }
}
