//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapSite2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Students()
        {
            this.Comments = new HashSet<Comments>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Stack { get; set; }
        public string Email { get; set; }
        public Nullable<int> GeneralRating { get; set; }
        public Nullable<int> PitchRating { get; set; }
        public Nullable<bool> EnableEmail { get; set; }
        public string PhotoPath { get; set; }
        public Nullable<int> Pin { get; set; }
        public Nullable<int> XP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
    }
}
